### ISSUE TITLE
Dynamic IP

### ISSUE THREAD

**Issue by d7eeem** [sealeo-org/openvpn#1]
Hi Great work in this container but a novice like me couldn't set this up because of my dynamic IP situation is there a way to add my domain to the config of the .ovpns Thanks in Advance

**Comment by cyrius** [comment]
Hello,
In ovpn you should have a line that start with 'remote' then an ip and after that the port.
Like this : remote 123.254.123.254 1194

You just have to replace the ip with your domain.
remote mydomain.com 1194

**Comment by d7eeem** [comment]
so dumb ... Thanks you kind sir
